---
framework: jest
preRun:
     command:
        - yarn install
        - yarn run build:lib
preMerge:
  pattern:
    - "./src/__tests__/*.spec.ts"
postMerge:
  pattern: 
    - "./src/__tests__/*.spec.ts"
postRun:
     command:
        - yarn --version
version: 1.0
